'use server'

import { createClient } from '@/src/lib/supabase/server'
import { revalidatePath } from 'next/cache'

async function getAuthContext() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Usuário não autenticado')
  return { supabase, user }
}

export async function getHistoricoPrecos(program: string, days: number) { try { const { supabase } = await getAuthContext(); const fromDate = new Date(); fromDate.setDate(fromDate.getDate() - days); const { data, error } = await supabase.from('market_prices').select('*').eq('programa', program.toUpperCase()).gte('timestamp', fromDate.toISOString()).order('timestamp', { ascending: true }); if (error) throw error; return data || [] } catch (error) { console.error('getHistoricoPrecos error', error); return [] } }
export async function getProgramaPrecos(program: string) { try { const { supabase } = await getAuthContext(); const start = new Date(); start.setHours(0,0,0,0); const { data, error } = await supabase.from('market_prices').select('*').eq('programa', program.toUpperCase()).gte('timestamp', start.toISOString()).order('timestamp', { ascending: false }); if (error) throw error; return data || [] } catch (error) { console.error('getProgramaPrecos error', error); return [] } }

export async function getRadarNoticias() { try { const { supabase } = await getAuthContext(); const { data, error } = await supabase.from('market_news').select('*').order('published_at', { ascending: false }); if (error) throw error; const items = data || []; return { active: items.filter((n: any) => n.is_active), expired: items.filter((n: any) => !n.is_active) } } catch (error) { console.error('getRadarNoticias error', error); return { active: [], expired: [] } } }

export async function toggleNoticiaAtiva(id: string) { try { const { supabase } = await getAuthContext(); const { data: current } = await supabase.from('market_news').select('is_active').eq('id', id).single(); const { error } = await supabase.from('market_news').update({ is_active: !current?.is_active }).eq('id', id); if (error) throw error; revalidatePath('/inteligencia'); return { success: true } } catch (error) { console.error('toggleNoticiaAtiva error', error); return { success: false } } }

export async function getAlertasConfig() { try { const { supabase, user } = await getAuthContext(); const { data, error } = await supabase.from('alertas_config').select('*').eq('user_id', user.id).order('created_at', { ascending: false }); if (error) throw error; return data || [] } catch (error) { console.error('getAlertasConfig error', error); return [] } }
export async function createAlertaConfig(payload: Record<string, unknown>) { try { const { supabase, user } = await getAuthContext(); const { error } = await supabase.from('alertas_config').insert({ ...payload, user_id: user.id }); if (error) throw error; revalidatePath('/inteligencia'); return { success: true } } catch (error) { console.error('createAlertaConfig error', error); return { success: false } } }
export async function updateAlertaConfig(id: string, payload: Record<string, unknown>) { try { const { supabase, user } = await getAuthContext(); const { error } = await supabase.from('alertas_config').update(payload).eq('id', id).eq('user_id', user.id); if (error) throw error; revalidatePath('/inteligencia'); return { success: true } } catch (error) { console.error('updateAlertaConfig error', error); return { success: false } } }
export async function deleteAlertaConfig(id: string) { try { const { supabase, user } = await getAuthContext(); const { error } = await supabase.from('alertas_config').delete().eq('id', id).eq('user_id', user.id); if (error) throw error; revalidatePath('/inteligencia'); return { success: true } } catch (error) { console.error('deleteAlertaConfig error', error); return { success: false } } }

export async function getOportunidades() { try { const { supabase, user } = await getAuthContext(); const today = new Date(); today.setHours(0,0,0,0); const [{ data: balances }, { data: prices }, { data: news }] = await Promise.all([supabase.from('balances').select('*, programs(*)').eq('user_id', user.id), supabase.from('market_prices').select('*').gte('timestamp', today.toISOString()), supabase.from('market_news').select('*').eq('is_active', true)]); const sell = (balances || []).flatMap((b: any) => { const program = (b.programs?.name || '').toUpperCase(); const daily = (prices || []).filter((p: any) => p.programa === program); if (!daily.length || Number(b.calculated_balance) <= 0) return []; const best = daily.sort((a:any,b:any)=>Number(b.valor)-Number(a.valor))[0]; const custo = Number(b.custo_medio||0); const atual = Number(best.valor||0); if (!custo || atual <= custo*1.1) return []; const saldo = Number(b.calculated_balance||0); return [{ tipo:'venda', programa:b.programs?.name, lucro_percentual:((atual-custo)/custo)*100, lucro_valor_estimado:(saldo/1000)*(atual-custo), melhor_comprador:best.plataforma, preco_atual:atual, custo_medio:custo, saldo_disponivel:saldo }] }); const userPrograms = new Set((balances || []).map((b: any) => (b.programs?.name || '').toUpperCase())); const transferencia = (news || []).filter((n:any)=>n.type==='promocao_transferencia').filter((n:any)=> userPrograms.has(String(n.program||'').toUpperCase()) || !n.program); const mercado = (news || []).filter((n:any)=>n.type!=='promocao_transferencia' && Number(n.bonus_percentage||0)>=80); return { sell, transferencia, mercado } } catch (error) { console.error('getOportunidades error', error); return { sell: [], transferencia: [], mercado: [] } } }
